import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/game.js';import {Input} from '../src/input.js';import {SaveStore,SAVE_KEY,sanitize} from '../src/save.js';import {Clock,STEP} from '../src/math.js';import {createLevel} from '../src/levels.js';
const memory=()=>{const data=new Map();return{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)}};
function setup(index=0){const storage=memory(),store=new SaveStore(storage),game=new Game(store),input=new Input();game.load(index,false);game.events=[];return{game,input,store,storage};}
function flat(g){g.level.platforms=[{id:999,x:0,y:620,w:g.level.width,h:480,kind:'ground',baseX:0,baseY:620}];for(const key of ['enemies','hazards','pickups','gates','winds','vents','coins','relics','shrines'])g.level[key]=[];Object.assign(g.player,{x:110,y:572,prevX:110,prevY:572,ground:true,vx:0,vy:0});}
function step(g,i,n=1){for(let k=0;k<n;k++)g.update(STEP,i);}
test('a held jump produces exactly one takeoff and retains flutter',()=>{const{game:g,input:i,store}=setup();flat(g);store.data.powers.push('glide');i.press('jump','jump');step(g,i,35);assert.equal(g.events.filter(e=>e.type==='jump').length,1);assert.equal(g.player.flutter,true);assert(g.player.y<572);i.release('jump');i.press('jump','jump');step(g,i);assert.equal(g.player.flutter,false);assert.equal(g.events.filter(e=>e.type==='flutter').length,1);});
test('jump buffer survives a near landing and triggers once',()=>{const{game:g,input:i}=setup();flat(g);g.player.y=556;g.player.vy=260;g.player.ground=false;i.press('jump','jump');step(g,i,20);assert.equal(g.events.filter(e=>e.type==='jump').length,1);assert(g.player.vy<0);});
test('coyote grace is consumed on takeoff',()=>{const{game:g,input:i}=setup();flat(g);g.player.ground=false;g.player.coyote=.06;i.press('jump','jump');step(g,i);assert(g.player.vy<0);assert.equal(g.player.coyote,0);});
test('fixed clock produces equal physics at 30,60,120 Hz rendering',()=>{const out=[];for(const hz of [30,60,120]){const{game:g,input:i}=setup();flat(g);i.press('right','right');const clock=new Clock();clock.advance(0,()=>{});for(let n=1;n<=hz*2;n++)clock.advance(n*1000/hz,dt=>g.update(dt,i));out.push(g.player.x);}assert(Math.max(...out)-Math.min(...out)<1e-6);});
test('different keys and pointers for the same action release independently',()=>{const i=new Input();i.press('ArrowRight','right');i.press('KeyD','right');i.press('pointer:1','right');i.release('KeyD');assert(i.down('right'));i.release('ArrowRight');assert(i.down('right'));i.release('pointer:1');assert(!i.down('right'));i.clear();assert.equal(i.edges.size,0);});
test('moving platforms carry riders horizontally and vertically',()=>{const{game:g,input:i}=setup();flat(g);g.level.platforms=[{id:8,x:100,y:500,baseX:100,baseY:500,w:250,h:20,kind:'raft',motion:{dx:65,dy:24,speed:.7,phase:0}}];Object.assign(g.player,{x:150,y:452,ground:true,support:8});step(g,i,120);assert(g.player.x>180);assert.equal(g.player.support,8);assert(Math.abs(g.player.y+48-g.level.platforms[0].y)<.1);});
test('ceiling stops ascending velocity for solid gates',()=>{const{game:g,input:i}=setup();flat(g);g.level.gates=[{id:'a',x:90,y:390,w:100,h:40,type:'rock'}];g.player.y=432;g.player.vy=-500;g.player.ground=false;step(g,i);assert.equal(g.player.vy,0);assert.equal(g.player.y,430);});
test('falls always recover even during invulnerability',()=>{const{game:g,input:i}=setup();g.player.y=1200;g.player.invincible=1;step(g,i);assert.equal(g.player.x,g.level.checkpoints[g.checkpoint].x);assert(g.player.y<700);});
test('storage denial does not prevent initialization or saving',()=>{const storage={getItem(){throw Error('Denied')},setItem(){throw Error('Quota')}};const store=new SaveStore(storage);const g=new Game(store);g.load(1,false);g.save();assert.equal(store.available,false);assert.equal(g.index,1);});
test('malformed fractional indexes are sanitized',()=>{const s=sanitize({current:1.5,unlocked:3.5,powers:['hack','ice'],attack:'hack'});assert.equal(s.current,0);assert.equal(s.unlocked,1);assert.deepEqual(s.powers,['bubble','ice']);assert.equal(s.attack,'bubble');});
test('checkpoint collectibles and shrine songs survive reload',()=>{const{game:g,store,storage}=setup();g.checkpoint=3;g.songs.add(0);g.coins.add(10);g.relics.add(1);g.elapsed=72;g.save();const reload=new Game(new SaveStore(storage));reload.load(0,true);assert.equal(reload.checkpoint,3);assert(reload.songs.has(0));assert(reload.coins.has(10));assert(reload.relics.has(1));assert.equal(reload.elapsed,72);assert.equal(reload.player.x,reload.level.checkpoints[3].x);});
test('legacy powers migrate without migrating incompatible coordinates',()=>{const storage=memory();storage.setItem('coquito-del-yunque-save-v3',JSON.stringify({currentLevel:3,permanentPowerups:{leafGlide:true,fireBall:true}}));const s=new SaveStore(storage);assert(s.data.powers.includes('fire'));assert(s.data.powers.includes('glide'));assert.equal(s.data.current,0);assert.equal(s.data.unlocked,1);});
test('chosen power survives changing levels',()=>{const{game:g,store}=setup();store.data.powers.push('fire');g.select('fire');g.load(1,false);assert.equal(store.data.attack,'fire');});
test('unlocked blooms cannot invisibly switch an attack',()=>{const{game:g,store,input:i}=setup();flat(g);store.data.powers.push('fire');g.select('fire');g.level.pickups=[{id:'old',type:'bubble',x:g.player.x,y:g.player.y,w:30,h:30}];step(g,i);assert.equal(store.data.attack,'fire');assert(!g.level.pickups[0].collected);});
test('Frost creates expiring collision geometry at impact',()=>{const{game:g,store,input:i}=setup();flat(g);store.data.powers.push('ice');g.select('ice');g.fire();step(g,i,125);assert(g.ice.length>0);assert(g.terrain().some(s=>s.kind==='ice'));step(g,i,620);assert.equal(g.ice.length,0);});
test('Flame removes thorns while other powers cannot',()=>{const{game:g,store,input:i}=setup();flat(g);g.level.gates=[{id:'thorns',x:205,y:480,w:30,h:140,type:'thorn'}];g.fire();step(g,i,30);assert(!g.broken.has('thorns'));store.data.powers.push('fire');g.select('fire');g.player.attack=0;g.fire();step(g,i,30);assert(g.broken.has('thorns'));assert(g.embers.length>0);});
test('Stone crushes spikes and rock barriers',()=>{const{game:g,store,input:i}=setup();flat(g);store.data.powers.push('stone');g.select('stone');g.level.hazards=[{id:1,x:240,y:602,w:45,h:18}];g.level.gates=[{id:'rock',type:'rock',x:320,y:470,w:40,h:150}];g.fire();step(g,i,110);assert(g.broken.has('spike-1'));assert(g.broken.has('rock'));});
test('Bubble chains to a second enemy',()=>{const{game:g,input:i}=setup();flat(g);g.level.enemies=[{id:0,x:250,y:582,w:38,h:38,hp:1,min:250,max:288,dir:1,speed:0,type:'beetle'},{id:1,x:340,y:582,w:38,h:38,hp:1,min:340,max:378,dir:1,speed:0,type:'beetle'}];g.fire();step(g,i,90);assert.equal(g.level.enemies.filter(e=>e.hp>0).length,0);});
test('completed levels persist explicitly including the final route',()=>{const{game:g,store,input:i}=setup(3);g.songs=new Set([0,1,2]);g.elapsed=200;g.finish();const x=g.player.x;i.press('right','right');step(g,i,120);assert.equal(g.player.x,x);assert.equal(g.mode,'complete');assert.equal(store.data.completed[3].time,200);assert.equal(store.data.unlocked,4);});
test('pausing freezes gameplay and resets safely',()=>{const{game:g,input:i}=setup();i.press('right','right');step(g,i,60);g.pause();const x=g.player.x,time=g.elapsed;step(g,i,120);assert.equal(g.player.x,x);assert.equal(g.elapsed,time);g.resume();step(g,i,10);assert(g.player.x>x);});
test('restart preserves permanent powers and removes current route collectibles',()=>{const{game:g,store}=setup();store.data.powers.push('fire');g.coins.add(1);g.songs.add(1);g.save();g.load(0,false);assert.equal(g.coins.size,0);assert.equal(g.songs.size,0);assert(g.own('fire'));});
for(let i=0;i<4;i++)test(`route ${i+1} has three shrines, safe spawn/checkpoints and multi-minute length`,()=>{const l=createLevel(i);assert.equal(l.shrines.length,3);assert.equal(l.relics.length,3);assert(l.width/320>115);assert(l.coins.length>100);for(const cp of l.checkpoints){assert(l.platforms.some(s=>s.y>=cp.y+48&&s.y<cp.y+80&&s.x<=cp.x&&s.x+s.w>=cp.x+38));assert(!l.hazards.some(h=>Math.abs(h.x-cp.x)<100));}const ids=l.platforms.map(p=>p.id);assert.equal(new Set(ids).size,ids.length);});
test('each shrine approach has reachable steps and triggers at its platform',()=>{for(let j=0;j<4;j++){const{game:g,input:i}=setup(j);for(const s of g.level.shrines){Object.assign(g.player,{x:s.x,y:s.y+80-48,ground:true,chirp:0});i.press('chirp','chirp');step(g,i);i.release('chirp');assert(g.songs.has(s.id));}}});
test('full route simulation reaches all four arches with all three songs',()=>{
 for(let level=0;level<4;level++){
  const{game:g,input:i,store}=setup(level);store.data.powers=['bubble','fire','ice','stone','glide','heart'];
  // A route bot uses normal movement and jumps. Shrine approaches are exercised separately above.
  g.songs=new Set([0,1,2]);i.press('right','right');let cooldown=0,maxX=0;
  for(let n=0;n<120*420&&g.mode==='playing';n++){
   cooldown--;const p=g.player;
   const support=g.terrain().find(s=>s.id===p.support);
   const edge=support?support.x+support.w-(p.x+p.w):Infinity;
   const danger=g.level.hazards.some(h=>!g.broken.has(`spike-${h.id}`)&&h.x>p.x&&h.x-p.x<105&&Math.abs(h.y-(p.y+p.h))<40);
   if((p.wall||(p.ground&&(edge<65||danger)))&&cooldown<=0){i.release('jump');i.press('jump','jump');cooldown=18;}
   if(p.attack<=0&&g.level.enemies.some(e=>e.hp>0&&e.x>p.x&&e.x-p.x<250)){i.release('attack');i.press('attack','attack');}
   // Select the correct bloom near a mandatory barrier, as taught by each route.
   const gate=g.level.gates.find(gate=>!g.broken.has(gate.id)&&gate.x>p.x&&gate.x-p.x<260);
   if(gate){g.select(gate.type==='thorn'?'fire':'stone');if(p.attack<=0){i.release('attack');i.press('attack','attack');}}
   step(g,i);maxX=Math.max(maxX,p.x);
  }
  assert.equal(g.mode,'complete',`Level ${level+1} stalls at ${maxX.toFixed(0)} / ${g.level.width}, deaths ${g.deaths}`);
 }
});
